### ISSUE TITLE
Expose log messages per cluster via API

### ISSUE THREAD

**Issue by Jan-M** [zalando-incubator/postgres-operator#105]
The API should allow access to a limited set of log lines per cluster to allow build a UI for the operator.

This could be some fixed size list per cluster to keep last ~ 100 lines.

Lines should have time, level, message to highlight errors later.

**Comment by ikitiki** [comment]
>This could be some fixed size list per cluster to keep last ~ 100 lines.
it's already there: https://github.com/zalando-incubator/postgres-operator/blob/master/pkg/util/config/config.go#L66

**Comment by ikitiki** [comment]
as for the log message, see:
https://github.com/zalando-incubator/postgres-operator/blob/master/pkg/spec/types.go#L80-L86

**Comment by Jan-M** [comment]
:+1: 

Now I just need API example :)
