### ISSUE TITLE
Delete kubernetes resources of the Clusters in the failed states

### ISSUE THREAD

**Issue by ikitiki** [zalando-incubator/postgres-operator#13]
We need to clean up kubernetes resources after failed (and maybe deleted) clusters.

The idea is to get list of kubernetes resources(Pods, Secrets, etc) using ``cluster_labels`` as a selector and match the resource to the corresponding cluster(using ``cluster_name_label``). if the cluster is in the failed status(``ClusterStatusUpdateFailed``, ``ClusterStatusAddFailed``), we can safely delete associated to that cluster resources

**Comment by Jan-M** [comment]
Do we need this? I would assume that the user would do only do two things:

a) fix his 3rd party object triggering the operator to propagate all changes until the cluster is running
b) delete 3rd party object indicating that the cluster will not be needed or is not desired anymore.

Delete you already have implemented so we should be fine?

**Comment by ikitiki** [comment]
probably we don't need to clean up kubernetes resources in case cluster failed to create/update.
But I guess we certainly need to clean up resources which do not belong to any cluster
