### ISSUE TITLE
Create the replica service

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando-incubator/postgres-operator#16]
For those use cases when one needs to access a replica. One needs to define it in the PostgreSQL manifest as well.

**Comment by Jan-M** [comment]
So what is the idea here: Just add a line in the third party object like

```
  enableReplicaService: true
```

I would initially not expect more. For AWS this would be an ELB + same source range.

**Comment by alexeyklyukin** [comment]
Yes, the MVP would look like this. There are some possibilities to extend it further, for instance, adding more labels (for directing traffic to only certain replicas), as contrary to the approach we have adopted for the master, the replica service should direct traffic based on labels, since typically there is more than one replica for the production databases.

The driver for this is a migration from the AWS, namely, there are some clusters for which the replica ELBs are used in addition to the master's one, so we cannot migrate them unless we create the missing replica service manually.

**Comment by alexeyklyukin** [comment]
Merged and deployed to production.
