### ISSUE TITLE
Run repair process for the failed clusters more often than the normal sync

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando-incubator/postgres-operator#230]
At the moment, the sync is called every ``resync_period`` and it simply goes to every clusters and check whether the actual state of the cluster matches the declared state in the manifest. That process is rather expensive, as it goes to all clusters and queries Kubernetes for cluster-related objects, therefore we try to bump up the ``resync_period`` to reduce the load on the API and free the workers to handle new clusters/changes to existing ones in a timely manner. However, a large ``resync_period`` also delays repair actions for the clusters that are known to be in a failed state (as some external actions, i.e. node failure, may have prevented the operator to create a healthy cluster initially.)

What we can do is to run sync on those clusters that we know are in the failed state more often by introducing a ``repair_period`` that will trigger sync only on the clusters that are in the failed state. This will cover both creation of Kubernetes objects and in-cluster databases and roles.  It will increase the availability of the clusters that fail due to some transient actions (i.e. Kubernetes decided to recreate the master pod at the time when we tried to update the cluster's manifest).

**Comment by mgomezch** [comment]
For the record, this arose from discussions around #213

**Comment by alexeyklyukin** [comment]
That has been implemented and merged at https://github.com/zalando-incubator/postgres-operator/pull/304
