### ISSUE TITLE
question: supporting readonly users

### ISSUE THREAD

**Issue by masiir** [zalando-incubator/postgres-operator#262]
I suppose this would be more of a feature request than an issue but here goes..

How do you see would it be possible to add users that have readonly access to databases within the cluster. This would be done with the cluster manifest. I'd like to have the entire database setup done once with the manifest and then "forget" it.

**Comment by Jan-M** [comment]
My quick answer is the following: We split users into two groups, one group comes from the team API and is expected to be users that "own" the database thus they get the admin role.

The second group of `users` for applications is specified in the manifest and they have 0 privileges by default. Only by referencing them in the `databases` part they get more power within a selected database.

So it boils down more to doing the right thing within your database and schema setup than the operator.

If this is not helpful maybe elaborate a bit more.
