### ISSUE TITLE
Why are there no public releases?

### ISSUE THREAD

**Issue by ieugen** [zalando-incubator/postgres-operator#296]
Hello, 

I'm looking to use a postgresql operator and I've found this one and the one from CrunchyData. 
There are a few things I check before I start using a new tool and one of that is the number of releases so far. 

I haven't seen any for this one and it seems like a solid tool. Could you please share the reason why there are no public releases so far? 

Also I have noticed the image is downloaded from a private repository. What happens if that repository goes away? 

The answers to my questions might be trivial, but I believe it is important to be spelled out.

Thanks, 
Eugen

**Comment by hjacobs** [comment]
@ieugen I can't answer why no public releases exist (the maintainers can answer this), I think it would be a good idea to tag and have proper releases!

Regarding the "private" registry: it's Zalando's Open Source registry, it's publicly readable and reasonably well maintained, there are many other projects using it, e.g. [External DNS](https://github.com/kubernetes-incubator/external-dns/releases). We generally recommend people to mirror production Docker images to their local Docker registry, e.g. we do the same for Docker Hub and gcr.io (we mirror the images we need and usually don't depend on them for production deployments). TL;DR: you should never rely on external registries you have no control over for production deployments, regardless of whether it's Zalando, Google or "official" Docker Hub.

**Comment by alexeyklyukin** [comment]
Hi @ieugen,

The operator is in heavy development right now. We are approaching our first public release and will put up a release tag (and notes) in the near future. It's rather stable though and used internally by Zalando.

It is quite trivial to build an image of the operator (IMAGE=your-repo-name TAG=your-tag make docker push). For the rest, I'd avoid duplicating the answer by @hjacobs above.
