### ISSUE TITLE
Handle max_connections and other 'special' Patroni settings correctly

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando-incubator/postgres-operator#297]
There are a couple of settings, namely, `max_connections`, `max_locks_per_transaction`, `max_worker_processes`, `max_prepared_transactions`, wal_level`', `wal_log_hints`, `track_commit_timestamp` that Patroni ignores unless they are set in the DCS section of the configuration `bootstrap/dcs/postgresql/parameters`.

https://patroni.readthedocs.io/en/latest/dynamic_configuration.html

The operator is, sadly, unaware of that, and treats them as other settings, putting them in `postgresq/parameters`. That means that any user settings take no effect and the only way to change any of the setting above is by exec-ing to the pod and running `patronictl  edit-config`.

The other part of the problem is that it is now impossible to clone a cluster with a non-default values for one of the parameter above (most frequently it happens with `max_connections`), as the replica won't start if it has a smaller (or just different) value for one of the parameters above.

**Comment by zerg-junior** [comment]
@alexeyklyukin Does the pr #298 closes this issue completely ?

**Comment by alexeyklyukin** [comment]
Another facade of this problem is the ability to change those settings from their initial values once the cluster is already running. Because of how Patroni handles the bootstrap section, it is not possible to do by changing the SPILO_CONFIGURATION variable generated by the operator. Therefore, our only option (besides doing ALTER SYSTEM, which will not propagate to new members automatically), is to call the Patroni API from the operator. 

The corner case here is deciding what to do in case an option like `max_connection` that used to be in the manifest disappears in the new iteration of it. While it would be tempting to set it to its default value from the operator, the operator has now knowledge of what default value for the option is, since that information is fully contained in Spilo. Therefore, the decision that makes most sense to me is to act only on options that are explicitly listed in the manifest.

Furthermore, since during the sync event it is not possible to reliably detect whether an option has changed or not (during the initial sync we don't really have old manifests to figure that out), and for the simplicity in the update case we can always call patroni API in case `max_connection` and other special options are present in the manifest. Patroni will do the right thing, which is do nothing in case those options didn't really change.

Right now, I will leave those options in the cluster configuration generated by the operator, which means that adding any of them would cause the pod rolling update (and also that we would rely on the rolling update to restart the pods and apply the new configuration instead of calling the patroni API to restart the pods). This is fine in most cases, however, it would break replicas if we try to reduce the max_connections: for that case we have to change the master first, wait until replicas replay all WAL segments generated by the master before the change and only then change the replicas. In practice, than kind of change is rather cumbersome to support in the operator, so I am willing to leave it as a documented issue.

**Comment by zerg-junior** [comment]
>  the decision that makes most sense to me is to act only on options that are explicitly listed in the manifest.

Explicitly added to the new version of a PG manifest or explicitly given default values in the operator manifest ?

>  that adding any of them would cause the pod rolling update 

adding == adding to the cluster manifest ?

**Comment by alexeyklyukin** [comment]
> Explicitly added to the new version of a PG manifest or explicitly given default values in the operator manifest ?

There are no default values for PostgreSQL parameters in the operator manifest.

> adding == adding to the cluster manifest ?

Yes

**Comment by zerg-junior** [comment]
Closed by #299

**Comment by fragsalat** [comment]
Is this deployed live already? Can I migrate my db cluster to a new namespace now :D?

**Comment by hjacobs** [comment]
@fragsalat what "live" are you talking about? This is the PostgreSQL Operator OSS repo and there is neither "deployment" nor "live" in this context :smirk:

**Comment by fragsalat** [comment]
True at some point^^ This isdue was raised for some point and I want to know if in my Zalando Cluster everything is ready to migrade to a new namespace^^
