### ISSUE TITLE
Missing configurable AWS zones. Currently hardcoded to "eu-central-1".

### ISSUE THREAD

**Issue by valer-cara** [zalando-incubator/postgres-operator#316]
This feature is marked as _todo_, but just adding a +1 to that :)

https://github.com/zalando-incubator/postgres-operator/blob/master/pkg/util/constants/aws.go#L8

I think I'll have to fork & build, hardcoding my own zone as _the quickest possible fix_

Thank you for all the hard work on postgres-operator!

**Comment by hjacobs** [comment]
As far as I can see this is a bug (hardcoded region, no config option), used here: https://github.com/zalando-incubator/postgres-operator/blob/cf663cb8417d7a58c88ccbde94d682b3c45b39f8/pkg/util/volumes/ebs.go#L23

**Comment by angapov** [comment]
Will it be fixed someday?

**Comment by zerg-junior** [comment]
@angapov i'll open the pr for that this week
