### ISSUE TITLE
Spilo image in example doesn't have resize2fs, resizes fail

### ISSUE THREAD

**Issue by valer-cara** [zalando-incubator/postgres-operator#317]
The example image to be used with the operator needs resize2fs installed to allow increasing cluster capacity: `registry.opensource.zalan.do/acid/spilo-cdp-10:1.4-p8`

https://github.com/zalando-incubator/postgres-operator/blob/master/manifests/configmap.yaml#L14

---

Sidenote: i found it hard to navigate images in the zalando registry:

- fetching a list of tags (`curl https://registry.opensource.zalan.do/v1/repositories/acid/spilo-cdp-10/tags`)
- no idea about dockerfiles used (unless intensive googling at times)

It'd help to have access to this info.

Thanks!

PS: having to change a single value in the manifest and get automatic resize, so good :fire:

**Comment by hjacobs** [comment]
1. better endpoint to list tags including timestamp: https://registry.opensource.zalan.do/teams/acid/artifacts/spilo-cdp-10/tags
2. all our Zalando Docker images contain a so-called `scm-source` to point to the source git repo and commit, here you go: https://registry.opensource.zalan.do/teams/acid/artifacts/spilo-cdp-10/tags/1.4-p13/scm-source

**Comment by valer-cara** [comment]
@hjacobs - Think i'm going full _unrelated_ to the original issue, but please allow me this. I've been trying to figure out the right spilo image to update to, but it's still very hard to see which _artifact_ to use (eg: demospilo, spilo, spilo-10, spilo-cdp-10, ...) and which tag. Even though there's the endpoint providing commit info, correlating the data is cumbersome so I can't really tell which image brings me what novelty.

Usually the git tag <-> docker image tag association feels fastest to navigate/identify (to me at least, but I've got patience to learn other conventions)

I then thought of building the images myself, for a bit more predictability, but i need to figure out how to do it since it uses Zappr from zalando, which deepens the mistery.

In the name of this great piece of software, the postgres operator, please send a helping hand to devs trying to wrap their heads around Spilo's strange image version management. 
Do you have any addional hints on how to follow these builds? Is there any other correlation except for that pier-one endpoint associating builds with commits?

**Comment by hjacobs** [comment]
@valer-cara thank you, I think this is valid feedback and IMHO both the PostgreSQL Operator and Spilo should use github releases to point to the correct latest release (and Docker image).

**Comment by Jan-M** [comment]
We have recently added the p8 release to the spilo release tab: https://github.com/zalando/spilo/releases

Oleksii is updating it to p11 as we speek.

For the operator we are aiming for the 1.0 once we have update the go client version to a more recent version to work with k8s 1.10+

A good source for the images to use imho is the example manifest we provide here.

**Comment by alexeyklyukin** [comment]
@valer-cara at the moment, using spilo-10:p11, but also check https://github.com/zalando/spilo/releases from time to time to see if there are new releases.
