### ISSUE TITLE
Unhealthy Pod can't be reinitalized if an update is scheduled

### ISSUE THREAD

**Issue by schmitch** [zalando-incubator/postgres-operator#341]
Currently I'm having trouble after "breaking" my pod.
I tried to force some restarts of the postgres operator by changing the max_connection setting, so that my pods get's rescheduled over an over.
somehow I tried to break it. after that I tried to move the data directory and reinitalize the pod with:
`patronictl -c postgres.yml reinit cluster-name cluster-name-1`

The command started successfully, however since there are still "running" updates the update-operator tries to patch the pod every `resync_period`, but since the reinit of a pod takes longer than the `resync_period` the pod will terminate and be inside a healthy state again.

The only way to actually "reinit" a pod if an update is scheduled, is therefore to scale the postgres-operator deployment to zero.
I guess there should be a way to check if there is an unhealty pod before trying to update the cluster.

**Comment by Jan-M** [comment]
Can you outline what you want to achieve? Changing max connections I believe no longer does a rolling upgrade as changing max connections uses the Patroni API.

You could change something else, just add a custom env var or bump the docker image?

In general you can also remove the operator and your cluster should function fine without it and you could fiddle with everything yourself until it is working again?

**Comment by schmitch** [comment]
well I somehow managed that the controller tries to schedule updates, so basically he tries to update my pod every x minutes. However my pod still tries to re-initialize.

That's why I think the operator should first check if one pod has the state `creating replica` before it patches any updates.

**Comment by Jan-M** [comment]
We have moved a lot of actions around, e.g. incl. resizing of disks, to all happen without constraints, this is actually important to fix broken clusters later on.

In theory the updates happening should all converge against a stable statefulset and no more syncs/changes required so I am wondering what is going on in your case.

**Comment by Jan-M** [comment]
Why does the operator decide to delete the pod over and over again? You should get this from the operator logs.

**Comment by schmitch** [comment]
Well I can't give the logs since I deleted them but I was able to reproduce it.
Also the Logs always told me that the postgres-operator made a -X PATCH to the master patroni, after that the patroni that was still creating a replica was actually terminated (I guess the process was killed, thus the pod restarted)

Basically reproduction steps on minikube:
1. have a cluster with a big enough database ~10gb should be enough
2. have a small resync_period, like 1 minute
3. change a value that will result in a rolling reboot of patroni
4. before the reboot happens, reinitialize your secondary.

after that the secondary will be broken since it will be restarted while it reinitalizes. also the postgres-operator will try to send a patch command to the patroni every resync_period, so even a manual action won't help since the above would happen again and again.

**Comment by schmitch** [comment]
postgres-operator:
```
time="2018-07-11T15:59:27Z" level=debug msg="syncing services" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T15:59:27Z" level=debug msg="syncing master service" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T15:59:27Z" level=debug msg="syncing replica service" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T15:59:27Z" level=debug msg="No load balancer created for the replica service" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T15:59:27Z" level=debug msg="syncing persistent volumes" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T15:59:28Z" level=debug msg="syncing statefulsets" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T15:59:28Z" level=info msg="found a statefulset with an unfinished pods rolling update" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T15:59:28Z" level=warning msg="Incomplete configuration for the Scalyr sidecar: all of SCALYR_API_KEY, SCALYR_SERVER_HOST and SCALYR_SERVER_URL must be defined" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T15:59:28Z" level=debug msg="rolling upgrade flag has been set to true" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T15:59:28Z" level=debug msg="calling Patroni API on a pod envisia-postgres/production-envisia-cluster-0 to set the following Postgres options: map[max_connections:110]" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T15:59:28Z" level=debug msg="making PATCH http request: http://10.244.54.165:8008/config" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T15:59:28Z" level=debug msg="performing rolling update" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T15:59:28Z" level=info msg="there are 2 pods in the cluster to recreate" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T15:59:28Z" level=debug msg="subscribing to pod \"envisia-postgres/production-envisia-cluster-1\"" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T15:59:57Z" level=info msg="pod \"envisia-postgres/production-envisia-cluster-1\" has been recreated" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T15:59:57Z" level=debug msg="unsubscribing from pod \"envisia-postgres/production-envisia-cluster-1\" events" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T15:59:57Z" level=debug msg="failing over from \"production-envisia-cluster-0\" to \"envisia-postgres/production-envisia-cluster-1\"" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T15:59:57Z" level=debug msg="making POST http request: http://10.244.54.165:8008/failover" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T15:59:57Z" level=debug msg="subscribing to pod \"envisia-postgres/production-envisia-cluster-1\"" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T16:00:18Z" level=warning msg="could not perform failover: could not failover: patroni returned 'Failover status unknown'" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T16:00:18Z" level=info msg="recreating old master pod \"envisia-postgres/production-envisia-cluster-0\"" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T16:00:18Z" level=debug msg="subscribing to pod \"envisia-postgres/production-envisia-cluster-0\"" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
time="2018-07-11T16:00:18Z" level=debug msg="unsubscribing from pod \"envisia-postgres/production-envisia-cluster-1\" events" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
```

sadly the pg log is missing but basically the log lines were:

* reinit in progress
* terminated after the above happend, I can reproduce it on saturday and post all the logs

**Comment by alexeyklyukin** [comment]
@schmitch from the operator logs it looks like Patroni could not fetch the status of the attached PostgeSQL, likely because PostgreSQL was not running

```
time="2018-07-11T16:00:18Z" level=warning msg="could not perform failover: could not failover: patroni returned 'Failover status unknown'" cluster-name=envisia-postgres/production-envisia-cluster pkg=cluster worker=0
```

Since that happened after changing max_connections (that one apparently worked), could it be that you were reducing the `max_connections` on the cluster?  Really interested in getting Postgres logs from the failing pod (you need to 'exec' into the pod and look for pgdata/pgroot/pg_log/postgresq-$weekdaynumber.log), it has probably crashed while replaying the WAL. 

Also, which version of Spilo do you deploy? If it is not the latest one, could you, please, update it to registry.opensource.zalan.do/acid/spilo-10:p11 and try again?

**Comment by alexeyklyukin** [comment]
@schmitch any updates on this?
