### ISSUE TITLE
how to use pgpool?

### ISSUE THREAD

**Issue by k1ng440** [zalando-incubator/postgres-operator#345]

**Comment by alexeyklyukin** [comment]
Hi,

This issues are for the postgres operator feature suggestions or bug reports.  Please, direct your question to  pgpool-general@pgpool.net.

**Comment by Jan-M** [comment]
If you feel like deploying pgpool in front of Postgres provided via the operator/patroni this should be pretty straight forward as there is a service that you can use as a target for pgpool.

How you deploy pgpool is up to you and Oleksii already pointet you to the community.
