### ISSUE TITLE
CRD-based configuration example missing

### ISSUE THREAD

**Issue by angapov** [zalando-incubator/postgres-operator#355]
In document https://github.com/zalando-incubator/postgres-operator/blob/master/docs/reference/operator_parameters.md in "CRD-based configuration" link to document https://github.com/zalando-incubator/postgres-operator/blob/wip/operator_configuration_via_crd/manifests/postgresql-operator-default-configuration.yaml is broken. Can you please fix it?

**Comment by alexeyklyukin** [comment]
@angapov fixed, thanks for reporting!
