### ISSUE TITLE
Support usage of another Dockerimage for "new" clusters.

### ISSUE THREAD

**Issue by Jan-M** [zalando-incubator/postgres-operator#36]
Basically to support easier testing and rolling out new features with less impact this could be useful.

The operator would pick the new Dockerimage for newly created clusters but would not touch existing stateful sets if their image is either the "new" or "current" Docker image.

**Comment by alexeyklyukin** [comment]
Done with https://github.com/zalando-incubator/postgres-operator/commit/6dcd074ea09500d70e10fa8ee0ea9a8c054ec5d6
