### ISSUE TITLE
single pod statefulset - failover

### ISSUE THREAD

**Issue by szuecs** [zalando-incubator/postgres-operator#363]
In a rolling node update, most often a single pod statefulset would be replicated before the rolling update and then the failover will be executed.
In some situations it seems not to work and sometimes I can fix it by restarting the postgres-operator and sometime I need to delete the postgres pod from the statefulset.

One indicator of this situation seems to be this warning:

```
time="2018-08-07T07:29:35Z" level=warning msg="could not move pod \"default/ale-app-config-0\": pod does not belong to 
a known cluster" pkg=controller
```

**Comment by Jan-M** [comment]
We started looking into this already yesterday. This is in our opinion a startup / race condition problem. During the rolling upgrade also the operator pod gets deleted and and during startup it may be notified of nodes becoming unscheduleable but the operator is not yet aware of all clusters.

**Comment by alexeyklyukin** [comment]
The fix has been merged. Basically, we let the operator populate the state of all PostgreSQL clusters before running the node informer. Since it is essentially one REST API call it won't delay the startup significantly.
