### ISSUE TITLE
Invalid regexp for rest api cluster status endpoint

### ISSUE THREAD

**Issue by miv** [zalando-incubator/postgres-operator#394]
Current apiserver regexp for cluster status is very narrow and doesn't support dashes in teamId.
https://github.com/zalando-incubator/postgres-operator/blob/master/pkg/apiserver/apiserver.go#L52

For example cluster with `teamId: "db-cluster-1"` will not be found using this regexp

**Comment by erthalion** [comment]
Thanks for reporting the issue, #400 should address the problem.
