### ISSUE TITLE
[RFC] Ensure minimum one healthy replica for 2-pod PG clusters

### ISSUE THREAD

**Issue by zerg-junior** [zalando-incubator/postgres-operator#402]
We have cases when a pod stucks during creation or runs with failing Postgres and/or Patroni (e.g. because of [delayed volume mounts by Kubernetes](https://github.com/kubernetes/kubernetes/issues/65392)). This means that the operator thinks a pod exists while the pod effectively does not work. 

This presents a problem for a common case of  a single-replica cluster if a pod fails. In such case we may consider  bootstraping a new replica from the master after timeout to ensure fault tolerance. This behavior can be built for example into the `Repair` scan.

**Comment by CyberDem0n** [comment]
In my opinion that doesn't make much sense.
Think about the case when the size of the data directory is a few TB. Creation of the new replica will take ages and will affect the performance of the master.

**Comment by Jan-M** [comment]
Imho this is also trying to solve a problem on the wrong level. This is a K8S/Infrastructure issue which the operator only in rare cases should try to work around. The operator should do the right decision ideally and not failover or give the infrastructure enough time to respond but additional code for workarounds should be avoided.

In general we should leave as many issues as possible with Kubernetes to solve.
