### ISSUE TITLE
Postgres operator cannot be created in non-default namespace

### ISSUE THREAD

**Issue by jens-totemic** [zalando-incubator/postgres-operator#403]
The installation manual mentions it's possible to run the operator in a namespace other than default. 
It states

> For example, to use the test namespace, run the following before deploying the operator's manifests:
>$ kubectl create namespace test
>$ kubectl config set-context --namespace=test
>$ kubectl create -f manifests/postgres-operator.yaml

When I do this, I get the following error message in the Kubernetes dashboard when inspecting the `postgres-operator` replica set:
```
Error creating: pods "postgres-operator-5fdccb5677-" is forbidden: error looking up service account test/zalando-postgres-operator: serviceaccount "zalando-postgres-operator" not found
```

I can only get the operator installed correctly if I use the `default` namespace. Is there another step I need to do in order to make it work? 

I'm using the latest manifests from the github repo. Steps to replicate the issue:
```
kubectl config set-context $(kubectl config current-context) --namespace=test
kubectl apply -f https://raw.githubusercontent.com/zalando-incubator/postgres-operator/master/manifests/configmap.yaml
kubectl apply -f https://raw.githubusercontent.com/zalando-incubator/postgres-operator/master/manifests/operator-service-account-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/zalando-incubator/postgres-operator/master/manifests/postgres-operator.yaml
```
and then observe the error in the replica set for the postgres-operator

**Comment by zerg-junior** [comment]
Hello, @jens-totemic 

Thanks for reaching out ! 

> Is there another step I need to do in order to make it work?

Files in `/manifests` are provided as examples only and are likely to need modifications. In this case you will need to replace the `default` namespace in `/manifests/operator-service-account-rbac.yaml `  with your target one because  service accounts and cluster role bindings are namespaced objects. The namespace value for the latter also cannot  be omitted in this file, i.e.  if you simply remove he namespace for the cluster role binding you will see 
>> The ClusterRoleBinding "zalando-postgres-operator" is invalid: subjects[0].namespace: Required value

**Comment by jens-totemic** [comment]
Hi @zerg-junior thanks for clarifying. I wasn't sure if `operator-service-account-rbac.yaml` was supposed to be used as is or not. I will modify it's namespace then. Thanks for your quick help!
