### ISSUE TITLE
Out-of-space according to /home/postgres/pgdata/pgroot/pg_log

### ISSUE THREAD

**Issue by excavador** [zalando-incubator/postgres-operator#431]
Our cluster stop working according to filled pg_log directory.
We recreated it and I see following:
```
# pwd
/home/postgres/pgdata/pgroot/pg_log
# du -hs *
0	postgresql-0.csv
55M	postgresql-1.csv
4.0K	postgresql-1.log
0	postgresql-2.csv
0	postgresql-3.csv
0	postgresql-4.csv
0	postgresql-5.csv
0	postgresql-6.csv
755M	postgresql-7.csv
56K	postgresql-7.log
#
```
Shipping log to s3 (both WAL and plain/csv logs) was configured, I see files in S3 (both WAL and once a day plain/csv logs).

Could you please give me advise, what and how I should to do with files inside `/home/postgres/pgdata/pgroot/pg_log` on my PersistentVolume?
Probably I missed some configuration option to auto-remove logs after uploading to S3?

**Comment by CyberDem0n** [comment]
Everything works as expected. Postgres is [configured](https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py#L199-L205) to write into one log file per day of the week (from 1 to 7). After one week it starts **overwriting** existing files.
In addition to that, there are 7 foreign [tables](https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/post_init.sh#L109-L112) in the "postgres" database. Basically, it gives you a possibility to access database logs via SQL.
Logging is not very [verbose](https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py#L135-L143). Having so big csv files usually is an indicator of some problems. Either you have `log_statement = all` on your application user or you have quite a lot of queries running longer than 500ms, or maybe some queries are writing a lot of temporary files, what also causing excessive logging.

In any case, neither postgres-operator nor Spilo nor Patroni are responsible for monitoring of your cluster. This is the task of your monitoring system. As I already mentioned, lack of free disk space is usually a very good indicator of some problems. And you should make a decision, fix problems or extend volume by updating cluster manifest.
