### ISSUE TITLE
Secret exists when postgresql resource be deleted

### ISSUE THREAD

**Issue by aixeshunter** [zalando-incubator/postgres-operator#432]
## Issue
In my k8s environment, I created a `postgresql` resource named `acid-pgcluster` in testdb namespace:
```bash
[root@master1~]# kubectl get postgresql -n testdb               
NAME             AGE
acid-pgcluster   10m

[root@master1 ~]# kubectl get po -n testdb
NAME               READY     STATUS    RESTARTS   AGE
acid-pgcluster-0   1/1       Running   0          6m
acid-pgcluster-1   1/1       Running   0          6m

[root@master1 ~]# kubectl get po -n testdb
NAME               READY     STATUS    RESTARTS   AGE
acid-pgcluster-0   1/1       Running   0          6m
acid-pgcluster-1   1/1       Running   0          6m
```

And then, I deleted the acid-pgcluster  `postgresql`  resource:
```bash
[root@master1 ~]# kubectl delete postgresql -n testdb acid-pgcluster
postgresql.acid.zalan.do "acid-pgcluster" deleted
```

After 30 seconds, I found `pod`, `sts`, `service` resources were all deleted, but the `secret` resource remained:
```bash
[root@master1 ~]# kubectl get secret -n testdb
NAME                                    TYPE                                  DATA      AGE
default-token-xqnh7                     kubernetes.io/service-account-token   3         27m
postgres.acid-pgcluster.credentials     Opaque                                2         16m
standby.acid-pgcluster.credentials      Opaque                                2         16m
zalando-postgres-operator-token-x85l9   kubernetes.io/service-account-token   3         16m
```

## yaml file
`postgersql.yaml`:
```bash
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-pgcluster
  namespace: testdb
spec:
  teamId: "ACID"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    # database owner
    zalando:
    - superuser
    - createdb
    testdb:
    - superuser
    - createdb

    # role for application foo
    foo_user:
  enableMasterLoadBalancer: true
  enableReplicaLoadBalancer: true
  #databases: name->owner
  databases:
    testdb: testdb
    foo: zalando
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 300m
      memory: 300Mi
  postgresql:
    version: "10"
```

## Version
```bash
registry.opensource.zalan.do/acid/postgres-operator:v1.0.0
```

## Question
Is this normal?

**Comment by erthalion** [comment]
Operator will not remove secrets for replication user and superuser (see this [code](https://github.com/zalando-incubator/postgres-operator/blob/master/pkg/cluster/cluster.go#L938)). Other than that you can check the log, because for every secret there should be a message with decision to remove or not.

**Comment by aixeshunter** [comment]
> Operator will not remove secrets for replication user and superuser (see this [code](https://github.com/zalando-incubator/postgres-operator/blob/master/pkg/cluster/cluster.go#L938)). Other than that you can check the log, because for every secret there should be a message with decision to remove or not.

@erthalion Hi, thanks for your answer. :)
But in my environment, `standby` is replication user and `postgres` is superuser,  user `zalando` and `testdb` all defined in `postgersql.yaml`:
```bash
  users:
    # database owner
    zalando:
    - superuser
    - createdb
    testdb:
    - superuser
    - createdb
```

So why user `testdb` be deleted but `zalando` remained?
