### ISSUE TITLE
List of images/releases?

### ISSUE THREAD

**Issue by redbaron** [zalando-incubator/postgres-operator#441]
Current operator references registry.opensource.zalan.do/acid/smoke-tested-postgres-operator:v1.0.0-21-ge39915c is there a way to see all available images? Even if it is not from the registry but lets say CI logs?

**Comment by Jan-M** [comment]
You can curl our open source docker registry under the above url or use the UI to list all images of the operator or spilo.

**Comment by Jan-M** [comment]
GET /teams/acid/artifacts/smoke-tested-postgres-operator/tags

via https://registry.opensource.zalan.do

**Comment by redbaron** [comment]
Thanks, that was helpful!
