### ISSUE TITLE
Allow child-objects to inherit labels from postgresql CR

### ISSUE THREAD

**Issue by stang** [zalando-incubator/postgres-operator#456]
In our kubernetes cluster, we currently have a `default-deny-all` `NetworkPolicy` and our CI/CD pipeline enforce users to declare a specific set of `labels` that are used in the `NetworkPolicy` and other comfort-features.

As we start to integrate the `postgres-operator`, we realized that users would create `postgresql` objects with these labels but `Pods`, `Services` and other objects that are created directly by the operator won't have them.

Therefore, we'd like to add a notion of `inherited_labels` to the `kubernetes` section of the operator configuration, which would be a list of labels that are whitelisted and that will be automatically added when the operator creates kubernetes objects (`StatefulSet`, `Pod`, `Service`, `Endpoints`, `pdb`).

**Comment by sdudoladov** [comment]
@FxKu you may be interested in this; cannot assign it to you for some weird reason :\

**Comment by FxKu** [comment]
Will look into it.

**Comment by FxKu** [comment]
I've added a second label to the [`cluster_labels`](https://github.com/zalando-incubator/postgres-operator/blob/9c7558816cdb0bfdbf65a52b624f23ae834a6c48/manifests/configmap.yaml#L7) field in the `ConfigMap` using this style `"application:spilo,foo:bar"` and it did show up for all the created objects.

Try it out and tell me, if this would work for you. Please, keep the default `application:spilo` label as the operator relies on it.

**Comment by stang** [comment]
Thanks @sdudoladov @FxKu !

The `cluster_labels` only allow to add a set of _static_ labels shared across all the clusters managed by the operator.

In our case, we need something _dynamic_: each postgres cluster being part of a different deployment would have their own labels (eg `{"app-instance": "foobar-123"}`).

I've pushed https://github.com/zalando-incubator/postgres-operator/pull/459 - please have a look and let me know if that would work for you.

I tried to make sure that the `extraLabels` are added only when generating objects, and never when  rendering `selector`, which should keep it fully backward compatible.

The only thing I noticed is that when deploying this new version of the operator for the first time, if there is any existing object, the operator will see that objects are not matching and re-create them, which can cause a small service disruption.

**Comment by sdudoladov** [comment]
> be a list of labels that are whitelisted and that will be automatically added

"whitelisted" as in "whitelisted in the CI/CD pipeline" ? 

> the operator re-create only StatefuleSet and Pod objects.

beware that this costs you a switchover done by the Patroni

> I've pushed #459

Thanks for the contribution :)

**Comment by Jan-M** [comment]
Yes and of those changes does trigger a rolling upgrades of pots, triggering a patroni failover. But this is expected, for any changes in the pod template.

Interesting use case, and interesting to see users of network policies

**Comment by stang** [comment]
> "whitelisted" as in "whitelisted in the CI/CD pipeline" ?
No, the idea was rather to be a list of whitelisted labels that are controlled by the k8s admins (cf: the ones who are deploying the `postgres-operator`).

> beware that this costs you a switchover done by the Patroni
Yes, we can't really avoid this as updating pod labels would automatically restart them by the nature of k8s.

It should not impact users that are not explicitly setting any `inherited_labels`, and it is disabled by default so it should be entirely transparent when users are updating the operator.
However, if they explicitly opt-in for this feature, the failover can't be avoided.

**Comment by stang** [comment]
Implemented by https://github.com/zalando-incubator/postgres-operator/pull/459
