### ISSUE TITLE
Investigate taint-based eviction for pod migration

### ISSUE THREAD

**Issue by sdudoladov** [zalando-incubator/postgres-operator#465]
The k8s v1.13 brings taint-based eviction to the beta stage and *enables it by default*. We need to investigate if
1.  at the bare minimum this mechanism does not affect master pod migration
2. if we can rely solely on this mechanism to migrate master pods away from decommissioned nodes.

related issues:
#429  #463

**Comment by redbaron** [comment]
I think whole work can be deferred to the Kubernetes and Patroni  like like following:

1. Patroni  updates  `tolerationSeconds` of a master pod for desired key, such as `node.kubernetes.io/unreachable` to be lower than replica's 

2. Patroni penalizes switchover candidates which are on tainted nodes

Net effect is that there is  only 1 switchover if situation in cluster allows it and as a bonus all failover/switchover decision is situated within Patroni, with no interference from Postgres operator (operator currently selects replicas to promote without taking into account their lag or other factors such as patroni tags, which doesn't look safe to me)

**Comment by redbaron** [comment]
on a second part: it is possible to add tolerations to any key of effect "NoExecute" 

```
  - effect: NoSchedule
    operator: Exists
     tolerationSeconds: 600
```

**Comment by sdudoladov** [comment]
I briefly documented the taint-based eviction; on our infra we did not run into problems with it.
