### ISSUE TITLE
Non "standard" registry

### ISSUE THREAD

**Issue by devlounge** [zalando-incubator/postgres-operator#483]
Hi,

Many companies have an internal registry syncing with a limited list of source registries like:

- Quay.io
- DockerHub
- GCR.io

Could your images be pushed to DockerHub as well / instead?

**Comment by Jan-M** [comment]
We can have a look at "as well". Need to find some account and credentials for this.

Likely though for now you would need to pull from us and push to your private registry manually.

**Comment by Jan-M** [comment]
Maybe more can chip in here if this is useful? Seems DockerHub is not that great for Orgs and using personal credentials makes it difficult to fit into our CI/CD.

**Comment by Jan-M** [comment]
Seems a similar discussion was done around other images we provide here:
https://github.com/kubernetes-incubator/external-dns/issues/479

So for now I will close this issue, with encourage users who have local registries to push there.

**Comment by devlounge** [comment]
That won't help getting this image approved in companies trusting only images from famous registries
