### ISSUE TITLE
postgres-operator on kubestack

### ISSUE THREAD

**Issue by pst** [zalando-incubator/postgres-operator#484]
I'm trying to include your postgres-operator in the relaunched [Kubestack catalog](https://www.kubestack.com/catalog/postgresql). However, the current release is rather old and I can currently only include releases in the catalog. Are there plans to cut a new release? CC @CyberDem0n because we spoke about this at Kubecon in Seattle.

**Comment by erthalion** [comment]
@Jan-M already second request for a new release, and probably it's a good time for that.

**Comment by erthalion** [comment]
@pst Here is a new release https://github.com/zalando-incubator/postgres-operator/releases/tag/v1.1.0
