### ISSUE TITLE
Logrus import string issue with Go modules builds

### ISSUE THREAD

**Issue by devlounge** [zalando-incubator/postgres-operator#491]
In all your files you use:
`github.com/Sirupsen/logrus`
instead of
`github.com/sirupsen/logrus`
which breaks builds done through go modules.

**Comment by devlounge** [comment]
Actually it seems solved in the latest code, but I took the code from the 1.0.0 release.
I usually only rely on releases.

**Comment by erthalion** [comment]
Yes, it was fixed at some point. Actually we may think about moving to build the project with go modules, and about a new release. I'll close this issue for now.

**Comment by erthalion** [comment]
@devlounge Here is a new release https://github.com/zalando-incubator/postgres-operator/releases/tag/v1.1.0
