### ISSUE TITLE
Empty loadBalancerSourceRanges allows LB access from everywhere

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando-incubator/postgres-operator#54]
If the user omits ``allowedSourceRanges`` field in the PostgreSQL manifest, the service generated from that spec lacks the ``loadBalancerSourceRanges`` restrictions. As a result, no restrictions is applied on the network access and the service is accessible from everywhere.

The most straightforward solution is to set the ``loadBalancerSourceRanges`` to 127.0.0.1/32 if ``allowedSourceRanges`` are empty, however, that would make the target load balancer unusable. 
I'd propose to consider ``allowedSourceRanges`` a mandatory field in the manifest. One can always emulate "free for all" with something like 0.0.0.0/0.

**Comment by Jan-M** [comment]
As we agreed on earlier, two things need to be implemented:

- [ ] if empty allow range we fall back to deny everything, as a safe default. This also presents a valid state for the LB security group to transition from and to without any kind of failure state for the cluster/operator.

- [ ] make the creation of the ELB optional, the default should be an operator config entry, as future deployments will only create K8S service for local access.
