### ISSUE TITLE
Release first version as Docker image on registry.opensource.zalan.do

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/postgres-operator#7]
I think the best approach would be to configure the Continuous Delivery Platform (`delivery.yaml`) to build and push Docker images to `registry.opensource.zalan.do/acid/postgres-operator:GIT_TAG`. Releases should be tagged in git and release notes should be available on https://github.com/zalando-incubator/postgres-operator/releases .

**Comment by Jan-M** [comment]
Solved via CDP publishing to open source registry.
