### ISSUE TITLE
Replace TPR with CRD

### ISSUE THREAD

**Issue by cbandy** [zalando-incubator/postgres-operator#98]
Kubernetes 1.7 has deprecated TPRs in favor of CRDs. See [blog post](http://blog.kubernetes.io/2017/06/kubernetes-1.7-security-hardening-stateful-application-extensibility-updates.html) and [release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#major-themes).

- https://coreos.com/blog/custom-resource-kubernetes-v17

**Comment by hjacobs** [comment]
Yes, makes absolutely sense, also the CRD validation was now merged for Kubernetes 1.8 :tada:
